#!/bin/bash
#SBATCH --time=2-23:55:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --job-name=seq2seq_new_20okt
#SBATCH --mem=15G
#SBATCH --mail-type=ALL
#SBATCH --mail-user=rikvannoord@gmail.com

module load Python/2.7.11-foss-2016a
module load tensorflow/0.9.0-foss-2016a-Python-2.7.11-CUDA-7.5.18

echo "Loading modules complete"

mkdir -p data/data_new/new_s400_l1_batch10
#mkdir -p checkpoints/checkpoints_new/new_s400_l1_batch10

python translate.py --batch_size 10 --data_dir data/data_new/new_s400_l1_batch10/ --train_dir checkpoints/checkpoints_new/new_s400_l1_batch_10_700k_door --size=400 --num_layers=1 --steps_per_checkpoint=5000 --train_file working/training/deft-p2-amr-r2-amrs-training-all.char --test_file working/dev/deft-p2-amr-r2-amrs-dev-all.char
