#!/bin/bash
#SBATCH --time=03:00:00
#SBATCH --ntasks=1
#SBATCH --job-name=test_new
#SBATCH --mem=1G
#SBATCH --mail-type=ALL
#SBATCH --mail-user=rikvannoord@gmail.com

module load requests/2.7.0-goolfc-2.7.11-Python-2.7.9
module load Python/2.7.11-foss-2016a
module load tensorflow/0.9.0-foss-2016a-Python-2.7.11

mkdir -p output/output_new/s400_l1_batch10_$1k/
mkdir -p output/output_new/s400_l1_batch10_$1k/test

python test_seq2seq_model.py -f ~/Documents/Seq2seq/working/test_char -df data/data_new/new_s400_l1_batch10 -tf checkpoints/checkpoints_new/new_s400_l1_batch_10_$1k/ -sf output/output_new/s400_l1_batch10_$1k/test -size 400 -layers 1
